### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by shukari** [LISTINGS09/ZEI#4]
- [x] gui for interiors
- [x] test garrison module/object switcher
- [x] a module which shows all buildings in the eden editor
- [x] addition to above, show buildings with none or only a few templates
- [x] make one base ZEI module

**Comment by LISTINGS09** [comment]
Quickly put something together for points 3 and 4. Is very useful to see what still needs to be done!

**Comment by shukari** [comment]
Will support you again in some days... much staff irl.
